version: '3.3'
services:
  cuoi-db:
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    container_name: cuoi_db
    volumes:
        - ./db:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: cuoiass
        MYSQL_DATABASE: cass
        MYSQL_USER: cass_admin
        MYSQL_PASSWORD: cass_admin123
        MYSQL_USER_1: cass_front
        MYSQL_PASSWORD_1: cass_admin123
    ports:
        - 23306:3306
    networks:
        app_net:
          ipv4_address: 172.30.0.4
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    container_name: cuoi_api
    ports:
      - 1234:80
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    environment:
      APP_NAME: API
      APP_ENV: local
      APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
      APP_DEBUG: "true"
      APP_URL: http://localhost:1234

      LOG_CHANNEL: stack

      DB_CONNECTION: mysql
      DB_HOST: 172.30.0.4
      DB_PORT: 3306
      DB_DATABASE: cass
      DB_USERNAME: cass_admin
      DB_PASSWORD: cass_admin123

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
    volumes:
      - ./cuoiass-api:/var/www/laravel
      - ./cuoiass-api/storage/logs:/var/www/storage/logs

  # cuoi-admin:
  #   build:
  #     dockerfile: docker/admin/Dockerfile
  #     context: .
  #   container_name: cuoi_admin
  #   ports:
  #     - 1235:80
  #   environment:
  #     APP_NAME: ADMIN
  #     APP_ENV: local
  #     APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
  #     APP_DEBUG: "true"
  #     APP_URL: http://localhost:1235
  #     API_URL: api
  #     LOG_CHANNEL: stack

  #     BROADCAST_DRIVER: log
  #     CACHE_DRIVER: file
  #     QUEUE_CONNECTION: sync
  #     SESSION_DRIVER: file
  #     SESSION_LIFETIME: 120


  #   volumes:
  #     - ./web-admin:/var/www/web-admin
  #     - ./web-admin/storage/logs:/var/www/storage/logs

  # cuoi-front:
  #   build:
  #     dockerfile: docker/front/Dockerfile
  #     context: .
  #   container_name: cuoi_front
  #   ports:
  #     - 1236:80
  #   environment:
  #     APP_NAME: CUSTOMER
  #     APP_ENV: local
  #     APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
  #     APP_DEBUG: "true"
  #     APP_URL: http://localhost:1236
  #     API_URL: api
  #     LOG_CHANNEL: stack

  #     BROADCAST_DRIVER: log
  #     CACHE_DRIVER: file
  #     QUEUE_CONNECTION: sync
  #     SESSION_DRIVER: file
  #     SESSION_LIFETIME: 120


  #   volumes:
  #     - ./web-front:/var/www/web-front
  #     - ./web-front/storage/logs:/var/www/storage/logs

  cuoi-vendor:
    build:
      dockerfile: docker/vendor/Dockerfile
      context: .
    container_name: cuoi_vendor
    ports:
      - 1237:80
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    environment:
      APP_NAME: CUSTOMER
      APP_ENV: local
      APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
      APP_DEBUG: "true"
      APP_URL: http://localhost:1237
      API_URL: 172.30.0.3/
      LOG_CHANNEL: stack
      API_PREFIX: "api"

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120


    volumes:
      - ./web-vendor:/var/www/web-vendor
      - ./web-vendor/storage/logs:/var/www/storage/logs

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
#         gateway: 172.30.0.1
