help:
	@echo "Run 'make build' to build docker."
	@echo "Run 'make push' to build docker."

build:
	@docker build -t rockerbom/cuoiass-base .
push:
	@echo "Pushing docker images..."
	@docker push rockerbom/cuoiass-base
